### ISSUE TITLE
j500h when?

### ISSUE THREAD

**Issue by nunopenim** [prototype74/SEPerienceKernel-MM_s3ve3g#2]
memory leak everywhere *angry guy with blue laser eyes sticker*

**Comment by prototype74** [comment]
> memory leak everywhere _angry guy with blue laser eyes sticker_

The title and your comment are pure... `Segmentation fault (core dumped)`

**Comment by nunopenim** [comment]
> The title and your comment are pure... `Segmentation fault (core dumped)`

wrong pointer

**Comment by prototype74** [comment]
> wrong pointer

Incompatible pointer type*
